id_key: ""
oauth_key: ""
server_url: "localhost:3000"
google_auth_id: ""
google_auth_secret: ""
google_openid_realm: "http://localhost:3000"
generator: "Kartta Labs Editor Server"
support_email: "someone@example.com"
email_from: "someone@example.com"
email_return_path: "someone@example.com"
sendgrid_api_key: ""
storage_url : "https://storage.googleapis.com"
