# The server protocol and host
server_protocol: "http"
server_url: "kartta-labs.example.com"
# Publisher
#publisher_url: ""
# The generator
generator: "Kartta Labs server"
copyright_owner: "Kartta Labs"
attribution_url: "http://example.org/copyright"
license_url: "http://opendatacommons.org/licenses/odbl/1-0/"
# Support email address
support_email: "kartta-labs@example.com"
# Sender addresses for emails
email_from: "Kartta Labs <kartta-labs@example.com>"
email_return_path: "kartta-labs@example.com"
# API version
api_version: "0.6"
# Application status - possible values are:
#   online - online and operating normally
#   api_readonly - site online but API in read-only mode
#   api_offline - site online but API offline
#   database_readonly - database and site in read-only mode
#   database_offline - database offline with site in emergency mode
status: "online"
# The maximum area you're allowed to request, in square degrees
max_request_area: 0.25
# Maximum number of nodes that will be returned by the api in a map request
max_number_of_nodes: 50000
# Maximum number of nodes that can be in a way (checked on save)
max_number_of_way_nodes: 2000
# The maximum area you're allowed to request notes from, in square degrees
max_note_request_area: 25
# Zoom level to use for postcode results from the geocoder
postcode_zoom: 15
# Zoom level to use for geonames results from the geocoder
geonames_zoom: 12
# Timeout for API calls in seconds
api_timeout: 300
# Timeout for web pages in seconds
web_timeout: 30
# Periods (in hours) which are allowed for user blocks
user_block_periods: [0, 1, 3, 6, 12, 24, 48, 96, 168, 336, 731, 4383, 8766, 87660]
# Rate limit for message sending
max_messages_per_hour: 60
# Domain for handling message replies
#messages_domain: "messages.example.org"
# Geonames authentication details
#geonames_username: ""
# GeoIP database
#geoip_database: ""
# Users to show as being nearby
nearby_users: 30
# Max radius, in km, for nearby users
nearby_radius: 50
# Spam threshold
spam_threshold: 50
# Delay diary entries from appearing in the feed for this many hours
diary_feed_delay: 0
# Default legale (jurisdiction location) for contributor terms
default_legale: hms
# Location of data for attachments
attachments_dir: ":rails_root/public/attachments"
# Log file to use
#log_path: ""
# Log file to use for logstash
#logstash_path: ""
# List of memcache servers to use for caching
#memcache_servers: []
# Enable legacy OAuth 1.0 support
oauth_10_support: true
# URL of Nominatim instance to use for geocoding
nominatim_url: "https://nominatim.openstreetmap.org/"
# Default editor
default_editor: "id"
# Imagery to return in capabilities as blacklisted
imagery_blacklist:
  # Current Google imagery URLs have google or googleapis in the domain
  # with a vt or kh endpoint, and x, y and z query parameters
  - ".*\\.google(apis)?\\..*/(vt|kh)[\\?/].*([xyz]=.*){3}.*"
  # Blacklist VWorld
  - "http://xdworld\\.vworld\\.kr:8080/.*"
  # Blacklist here
  - ".*\\.here\\.com[/:].*"
# URL of Overpass instance to use for feature queries
overpass_url: ""
# Routing endpoints
graphhopper_url: ""
fossgis_osrm_url: ""
# Enforce Content-Security-Policy
csp_enforce: false
# URL for reporting Content-Security-Policy violations
#csp_report_url: ""
# Storage service to use in production mode
storage_service: "local"
# Root URL for storage service
# storage_url:
# SMTP credentials
#smtp_address: ""
#smtp_port: 
#smtp_username:""
#smtp_password:""
# SendGrid Credentials
#sendgrid_api_key:""
